GENERAL:
  MANUAL_SEED: 123
  # CHECKPOINT_PATH: "/usr/stud/gaj/ssc/semantic-scene-completion/semantic-scene-completion/experiments/305/modelFULL-10.pth"
  TEACHER_CHECKPOINT_PATH: "/usr/stud/gaj/ssc/semantic-scene-completion/semantic-scene-completion/experiments/303/teacherFULL-14.pth"
  EXPERIMENT_NAME: "segpriors-larger"
  LEVEL: "FULL"
MODEL:
  DISTILLATION: False
  DISTILLATION_SAMPLES: 2
  SEG_HEAD: True
  RECTIFY_LABELS: False
  NUM_INPUT_FEATURES: 32
  NUM_OUTPUT_CHANNELS: 32

TRAIN:
  NUM_WORKERS: 8
  BATCH_SIZE: 1

SOLVER:
  BASE_LR: 0.0002