GENERAL:
  MANUAL_SEED: 123
  # CHECKPOINT_PATH: "/usr/src/app/semantic-scene-completion/experiments/198/model128-71.pth"
  # OVERFIT: True
  # NUM_SAMPLES_OVERFIT: 
# SEGMENTATION:
#   CHECKPOINT: "/usr/src/app/semantic-scene-completion/experiments/008/modelFULL-9.pth"
# MODEL:
#   OCCUPANCY_128_WEIGHT: 0.2
#   OCCUPANCY_256_WEIGHT: 4.0
#   OCCUPANCY_64_WEIGHT: 0.1
#   SEMANTIC_128_WEIGHT: 0.2
#   SEMANTIC_256_WEIGHT: 2.0
#   SEMANTIC_64_WEIGHT: 0.1

# SOLVER:
#   BASE_LR: 0.001